language: python
sudo: false
python:
  - 2.7
addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libfftw3-dev
    - libopenmpi-dev
    - openmpi-bin
env:
  # Test all fast tests in Debug build:
  - BUILD_TYPE="Debug" TEST_OPENMP="yes"
  # Test all fast tests in Debug build with libint:
  - TEST_LIBINT="yes" BUILD_TYPE="Debug" TEST_OPENMP="yes"
  # Test all fast tests in Debug build with FFTW:
  - TEST_FFTW="yes"  BUILD_TYPE="Debug" TEST_OPENMP="yes"
  # Test all slow tests in Release build (to make them run faster) and disable OpenMP due to #12:
  - TEST_SLOW="yes" BUILD_TYPE="Release"
  # Test all Python tests in Debug build:
  - BUILD_TYPE="Debug" TEST_PYTHON="yes" TEST_OPENMP="yes"
  # Test all MPI tests in Debug build:
  - TEST_MPI="yes"  BUILD_TYPE="Debug" TEST_OPENMP="yes"
before_install:
  - if [[ "${TEST_LIBINT}" == "yes" ]]; then
      git clone https://github.com/qsnake/libint.git;
      pushd libint;
      ./configure --prefix=$HOME/usr > conf_log;
      make;
      make install;
      popd;
    fi
  - if [[ "${TEST_PYTHON}" == "yes" ]]; then
      pip install -q --use-mirrors cython==0.17.1 numpy==1.6.2 sympy==0.7.1;
      pip install -q --use-mirrors matplotlib==1.1.1;
    fi
before_script:
  - bin/install_travis.sh
script:
  - bin/test_travis.sh
notifications:
  email: false
