# This file is automatically generated by fparser from 'src/c_hfsolver.f90'.
# Do not edit by hand (rerun fparser instead).

from libcpp cimport bool

cdef extern from "c_hfsolver.h":

    void hfsolver_Inu(int *k, double *x, double *r)
    void hfsolver_Knu(int *k, double *x, double *r)
