// This file is automatically generated by fparser from 'src/c_hfsolver.f90'.
// Do not edit by hand (rerun fparser instead).

#ifndef _c_hfsolver_h
#define _c_hfsolver_h

#include <stdbool.h>

#if defined (__cplusplus)
extern "C" {
#endif

void hfsolver_Inu(int *k, double *x, double *r);
void hfsolver_Knu(int *k, double *x, double *r);

#if defined (__cplusplus)
}
#endif

#endif
