find_path(UMFPACK_INCLUDE_DIR umfpack.h NO_DEFAULT_PATH)
find_path(UMFPACK_INCLUDE_DIR umfpack.h)
find_library(UMFPACK_LIBRARY umfpack ${UMFPACK_LIBRARY_DIRS} NO_DEFAULT_PATH)
find_library(UMFPACK_CHOLMOD_LIBRARY cholmod ${UMFPACK_LIBRARY_DIRS} NO_DEFAULT_PATH)
find_library(UMFPACK_CAMD_LIBRARY camd ${UMFPACK_LIBRARY_DIRS} NO_DEFAULT_PATH)
find_library(UMFPACK_CCOLAMD_LIBRARY ccolamd ${UMFPACK_LIBRARY_DIRS} NO_DEFAULT_PATH)
find_library(UMFPACK_COLAMD_LIBRARY colamd ${UMFPACK_LIBRARY_DIRS} NO_DEFAULT_PATH)
find_library(UMFPACK_AMD_LIBRARY amd ${UMFPACK_LIBRARY_DIRS} NO_DEFAULT_PATH)
find_library(UMFPACK_SUITESPARSECONFIG_LIBRARY suitesparseconfig ${UMFPACK_LIBRARY_DIRS} NO_DEFAULT_PATH)

set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARY} ${UMFPACK_CHOLMOD_LIBRARY}
    ${UMFPACK_CAMD_LIBRARY} ${UMFPACK_CCOLAMD_LIBRARY}
    ${UMFPACK_COLAMD_LIBRARY} ${UMFPACK_AMD_LIBRARY}
    ${UMFPACK_SUITESPARSECONFIG_LIBRARY})
set(UMFPACK_INCLUDE_DIRS ${UMFPACK_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(UMFPACK DEFAULT_MSG
    UMFPACK_LIBRARY UMFPACK_CHOLMOD_LIBRARY
    UMFPACK_CAMD_LIBRARY UMFPACK_CCOLAMD_LIBRARY UMFPACK_COLAMD_LIBRARY
    UMFPACK_AMD_LIBRARY UMFPACK_SUITESPARSECONFIG_LIBRARY
    UMFPACK_INCLUDE_DIR)

mark_as_advanced(UMFPACK_INCLUDE_DIR UMFPACK_LIBRARY UMFPACK_CHOLMOD_LIBRARY
    UMFPACK_CAMD_LIBRARY UMFPACK_CCOLAMD_LIBRARY UMFPACK_COLAMD_LIBRARY
    UMFPACK_AMD_LIBRARY UMFPACK_SUITESPARSECONFIG_LIBRARY)
